<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalGovernmentSeeder extends Seeder
{

    public function run()
    {
        DB::table('local_governments')->insert([
            ['name' => 'Aba North',        'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aba South',        'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arochukwu',        'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bende',             'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ikwuano',      'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Isiala Ngwa North',  'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Isiala Ngwa South',  'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Isuikwuato',          'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Obi Ngwa',     'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ohafia',        'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Osisioma',      'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ugwunagbo',     'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ukwa East',     'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ukwa West',       'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umuahia North',    'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umuahia South',    'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umu Nneochi',     'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],



            ['name' => 'Abaji',       'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abuja Municipal Area Council',   'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bwari',       'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gwagwalada',       'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kuje',       'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kwali',       'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],




            ['name' => 'Demsa',   'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fufure',  'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ganye',   'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gayuk',    'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Girei',  'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gombi',    'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Hong',     'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jada',   'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
              ['name' => 'Lamurde',     'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Madagali',     'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Maiha',      'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mayo Belwa',      'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Michika',       'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mubi North',     'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Mubi South',      'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Numan',     'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
              ['name' => 'Ganye',       'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Madagali',      'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Shelleng',        'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gayuk',     'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Maiha',        'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Maiha',      'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Girei',        'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mayo Belwa',    'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Toungo',       'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gombi',           'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Michika',         'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yola North',       'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Hong',             'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mubi North',       'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['name' => 'Yola South',     'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],





             ['name' => 'Abak',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ibesikpo Asutan', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mbo',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oron',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eastern Obolo',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ibiono-Ibom',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mkpat-Enin',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oruk Anam',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eket',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ika',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nsit-Atai',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Udung-Uko',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Esit Eket',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ikono',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nsit-Ibom',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ukanafun',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Essien Udim',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ikot Abasi',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nsit-Ubium',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uruan',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Etim Ekpo',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ikot Ekpene',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Obot Akara',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Urue-Offong/Oruko',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Etinan',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ini',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Okobo',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uyo',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ibeno',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Itu',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Onna',       'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],



        ////ANAMBRA STATE  state id = 5
            ['name' => 'Aguata',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dunukofia',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nnewi South',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Anambra East',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ekwusigo',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ogbaru',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ekwusigo',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ogbaru',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Anambra West',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Idemili North',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Onitsha North',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Anaocha',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Idemili South',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Onitsha South',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Awka North',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ihiala',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Orumba North',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Awka South',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Njikoka',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Orumba South',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ayamelum',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nnewi North',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oyi',       'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],





  //  bauchi  state id = 6
    ['name' => 'Alkaleri',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Ganjuwa',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Ningi',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Bauchi',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Giade',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Shira',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Bogoro',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Itas/Gadau',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Tafawa Balewa',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Damban',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Jamaare',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Toro',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Darazo',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Katagum',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Warji',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Dass',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Kirfi',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Warji',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Gamawa',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Misau',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Zaki',       'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],

///bayelsa state id = 7
['name' => 'Brass',       'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ekeremor',       'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kolokuma/Opokuma',       'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Nembe',       'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ogbia',       'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Sagbama',       'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Southern Ijaw',       'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Yenagoa',       'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],





//Benue State  state id = 8
['name' => 'Ado',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Agatu',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Apa',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gboko',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Guma',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gwer East',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gwer West',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Katsina-Ala',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Konshisha',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kwande',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Logo',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Makurdi',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Obi',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ogbadibo',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ohimini',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Oju',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Okpokwu',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Oturkpo',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Tarka',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ukum',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ushongo',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Vandeikya',       'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],




/// Borno State state id = 9
['name' => 'Abadam',       'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Askira/Uba',    'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Guzamala',       'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Mafa',       'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gwoza',       'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Magumeri',     'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bama',       'state_id' => 9,'created_at' => now(), 'updated_at' => now()],
['name' => 'Hawul',       'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Maiduguri',   'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bayo',       'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Jere',      'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Marte',      'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Biu',       'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Chibok',      'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Damboa',      'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Dikwa',      'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gubio',       'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kaga',       'state_id' => 9,'created_at' => now(), 'updated_at' => now()],
['name' => 'Kala/Balge',    'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Konduga',      'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kukawa',      'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kwaya Kusar',    'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Mobbar',   'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Monguno',  'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ngala',     'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Nganzai',  'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Shani',    'state_id' => 9, 'created_at' => now(), 'updated_at' => now()],






///CROSS RIVER  state id = 10;

['name' => 'Abi',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Akamkpa',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => ' Akpabuyo',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bakassi',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bekwarra',         'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Biase',        'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],

  ['name' => 'Boki',         'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Calabar Municipal',  'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Calabar South',     'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Etung',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ikom',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Obanliku',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Obubra',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Obudu',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Odukpani',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ogoja',       'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Yakuur',         'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Yala',         'state_id' => 10, 'created_at' => now(), 'updated_at' => now()],


//delta state state id = 11
['name' => 'Aniocha North',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Aniocha South',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bomadi',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Burutu',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ethiope East',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ethiope West',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Aniocha North',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Aniocha South',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ethiope East',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ethiope West',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ika North East',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ika South',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Isoko North',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Isoko South',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ndokwa East',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ndokwa West',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Okpe',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Oshimili North',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Oshimili South',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Patani',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Sapele',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Udu',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ughelli North',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ughelli South',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ukwuani',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Uvwie',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Warri North',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Warri South',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Warri South West',       'state_id' => 11, 'created_at' => now(), 'updated_at' => now()],






 //////Ebonyi State  state_id = 12
 ['name' => 'Abakaliki',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Afikpo North',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
  ['name' => 'Afikpo South (Edda)',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ebonyi',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ezza North',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ezza South',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ikwo',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ishielu',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ivo',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Izzi',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ohaozara',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ohaukwu',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Onicha',       'state_id' => 12, 'created_at' => now(), 'updated_at' => now()],


//  Edo State state_id = 13
 ['name' => 'Akoko-Edo',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Egor',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Esan Central',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Esan North-East',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Esan South-East',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Esan West',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Etsako Central',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
  ['name' => 'Etsako East',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Igueben',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ikpoba Okha',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Orhionmwon',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Oredo',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ovia North-East',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ovia South-West',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Owan East',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Owan West',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Uhunmwonde',       'state_id' => 13, 'created_at' => now(), 'updated_at' => now()],





///Ekiti State   state id = 14

 ['name' => 'Ado Ekiti',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Gbonyin',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Irepodun/Ifelodun',  'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Efon',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ido Osi',       'state_id' =>14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ise/Orun',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ekiti East',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ijero',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
  ['name' => 'Moba',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ekiti South-West',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ikere',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Oye',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ekiti West',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ikole',       'state_id' =>14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ekiti West',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'ikole',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'emure',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Oye',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'ilejemeje',       'state_id' => 14, 'created_at' => now(), 'updated_at' => now()],

 ['name' => 'Aninri',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Awgu',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Enugu East',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Enugu North',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Enugu South',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ezeagu',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Igbo Etiti',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Igbo Eze North',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Igbo Eze South',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Isi Uzo',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Nkanu East',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Nkanu West',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Nsukka',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Oji River',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Udenu',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Udi',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Uzo-Uwani',       'state_id' => 15, 'created_at' => now(), 'updated_at' => now()],



['name' => 'Akko',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Balanga',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Billiri',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Dukku',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Funakaye',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Gombe',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Kaltungo',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Kwami',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Nafada',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Shongom',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Yamaltu/Deba',       'state_id' => 16, 'created_at' => now(), 'updated_at' => now()],


 
['name' => 'Aboh Mbaise',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ahiazu Mbaise',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ehime Mbano',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ezinihitte',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ideato North',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ideato South',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ihitte/Uboma',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ikeduru',               'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Isiala Mbano',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Isu',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Mbaitoli',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ngor Okpala',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Njaba',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Nkwerre',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Nwangele',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Obowo',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Oguta',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ohaji/Egbema',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Okigwe',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Orlu',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Orsu',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Oru East',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Oru West',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Owerri Municipal',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Owerri North',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Owerri West',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Unuimo',       'state_id' => 17, 'created_at' => now(), 'updated_at' => now()],

 ['name' => 'Auyo',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Babura',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Biriniwa',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Birnin Kudu',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Buji',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Dutse',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Gagarawa',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Garki',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Garki',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Gumel',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Guri',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Gwaram',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Gwiwa',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Hadejia',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Jahun',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Kafin Hausa',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Kaugama',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Kazaure',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Kiri Kasama',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Kiyawa',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Maigatari',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Malam Madori',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Miga',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ringim',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Malam Madori',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Miga',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Ringim',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Roni',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Sule Tankarkar',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Taura',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],
 ['name' => 'Yankwashi',       'state_id' => 18, 'created_at' => now(), 'updated_at' => now()],



   /// / Kaduna State state = 19

   ['name' => 'Birnin Gwari',       'state_id' => 19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Chikun',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Giwa',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Igabi',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ikara',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Jaba',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Jemaa',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kachia',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kaduna North',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kaduna South',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kagarko',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kajuru',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kauru',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kaura',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kubau',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kudan',       'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Lere',        'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Makarfi',     'state_id' =>  19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Sabon Gari',  'state_id' => 19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Sanga',       'state_id' => 19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Soba',        'state_id' => 19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Zangon Kataf','state_id' => 19, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Zaria',       'state_id' => 19, 'created_at' => now(), 'updated_at' => now()],


  // Kano State  state id = 20
   ['name' => 'Ajingi',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Albasu',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Bagwai',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Bebeji',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Bichi',        'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Bunkure',      'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dala',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dambatta',     'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dawakin Kudu', 'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dawakin Tofa', 'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Doguwa',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Fagge',        'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Gabasawa',     'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Garko',        'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Garun Mallam', 'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Gaya',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Gezawa',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Gwale',        'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Gwarzo',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kabo',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kano Municipal',  'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Karaye',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kibiya',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kiru',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kumbotso',     'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kunchi',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kura',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Madobi',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Makoda',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Minjibir',     'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Nasarawa',     'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Rano',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Rimin Gado',    'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Rogo',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Shanono',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Sumaila',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Takai',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Tarauni',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Tofa',          'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Tsanyawa',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Tudun Wada',       'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ungogo',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Warawa',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Wudil',         'state_id' => 20, 'created_at' => now(), 'updated_at' => now()],



  // Katsina State

   ['name' => 'Bakori',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Batagarawa',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Batsari',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Baure',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Bindawa',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Charanchi',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dandume',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Danja',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dan Musa',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Daura',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dutsi',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dutsin Ma',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Faskari',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Funtua',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ingawa',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Jibia',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kafur',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kaita',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kankara',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kankia',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Katsina',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kurfi',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kusada',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'MaiAdua',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Malumfashi',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Mani',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Mashi',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Matazu',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Musawa',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Rimi',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Sabuwa',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Safana',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Sandamu',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Zango',       'state_id' => 21, 'created_at' => now(), 'updated_at' => now()],



  /// Kebbi State

   ['name' => 'Aleiro',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Argungu',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Augie',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Bagudo',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Birnin Kebbi',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Bunza',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dandi',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Gwandu',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Fakai',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Arewa Dandi',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Jega',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kalgo',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Koko/Besse',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Maiyama',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ngaski',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Sakaba',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Shanga',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Suru',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Wasagu/Danko',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Yauri',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Zuru',       'state_id' => 22, 'created_at' => now(), 'updated_at' => now()],


  ///// Kogi State

   ['name' => 'Adavi',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ajaokuta',        'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ankpa',        'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Bassa',        'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Dekina',        'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ibaji',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Idah',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Igalamela Odolu',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ijumu',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Kabba/Bunu',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Kogi',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Lokoja',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
    ['name' => 'Mopa Muro',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ofu',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Ogori/Magongo',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Okehi',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Okene',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Omala',            'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Yagba East',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Yagba East',       'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Olamaboro',        'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],
   ['name' => 'Yagba West',        'state_id' => 23, 'created_at' => now(), 'updated_at' => now()],



    // Kwara State

     ['name' => 'Asa',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Baruten',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Edu',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ekiti',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ifelodun',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ilorin East',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ilorin South',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ilorin West',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Irepodun',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Isin',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Kaiama',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Moro',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Offa',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Oke Ero',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Oyun',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Pategi',       'state_id' => 24, 'created_at' => now(), 'updated_at' => now()],



    // Lagos State
     ['name' => 'Agege',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ajeromi-Ifelodun',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Alimosho',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Amuwo-Odofin',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Apapa',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Badagry',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Epe',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Eti Osa',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ibeju-Lekki',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ifako-Ijaiye',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ikeja',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ikorodu',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Kosofe',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Lagos Island',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Lagos Mainland',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Mushin',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ojo',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Oshodi-Isolo',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Shomolu',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Surulere',       'state_id' => 25, 'created_at' => now(), 'updated_at' => now()],



   //  Nasarawa State
     ['name' => 'Akwanga',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Awe',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Doma',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Karu',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Keana',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Keffi',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Kokona',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Lafia',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Nasarawa',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Nasarawa Egon',  'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Obi',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Toto',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Wamba',       'state_id' => 26, 'created_at' => now(), 'updated_at' => now()],



     //Niger State
     ['name' => 'Agaie',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Agwara',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Bida',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Borgu',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Bosso',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Chanchaga',    'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Edati',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Gbako',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Gurara',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Katcha',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Kontagora',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Lapai',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Lavun',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Magama',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Mariga',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Mashegu',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Mokwa',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Moya',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Paikoro',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Rafi',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Rijau',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Shiroro',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Suleja',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Tafa',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Wushishi',       'state_id' => 27, 'created_at' => now(), 'updated_at' => now()],




     //Ogun State

     ['name' => 'Abeokuta North',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Abeokuta South',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ado-Odo/Ota',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ewekoro',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ifo',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ijebu East',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ijebu North',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ijebu North East',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ijebu Ode',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ikenne',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Imeko Afon',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ipokia',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Obafemi Owode',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Odeda',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Odogbolu',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ogun Waterside',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Remo North',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Shagamu',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Yewa North',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Yewa South',       'state_id' => 28, 'created_at' => now(), 'updated_at' => now()],



   //  Ondo State
     ['name' => 'Akoko North-East',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Akoko North-West',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Akoko South-East',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Akoko South-West',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Akure North',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Akure South',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ese Odo',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Idanre',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ifedore',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ilaje',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ile Oluji/Okeigbo',  'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Irele',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Odigbo',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Okitipupa',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ondo East',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
      ['name' => 'Ondo West',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'ose',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'owo',       'state_id' => 29, 'created_at' => now(), 'updated_at' => now()],



    // Osun State

     ['name' => 'Aiyedaade',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Aiyedire',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Atakunmosa East',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Atakunmosa West',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Boluwaduro',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Boripe',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ede North',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ede South',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Egbedore',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ejigbo',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ife Central',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ife East',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ife North',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ife South',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ifedayo',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ifelodun',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ila',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ilesa East',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ilesa West',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Irepodun',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Irewole',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Isokan',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Iwo',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Obokun',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Odo Otin',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Ola Oluwa',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Olorunda',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Oriade',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Orolu',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],
     ['name' => 'Osogbo',       'state_id' => 30, 'created_at' => now(), 'updated_at' => now()],





     //Oyo State

['name' => 'Afijio',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Akinyele',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Atiba',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Atisbo',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Egbeda',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibadan North',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibadan North-East',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibadan North-West',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibadan South-East',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibadan South-West',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibarapa Central',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibarapa East',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibarapa North',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ido',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Irepo',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Iseyin',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Itesiwaju',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Iwajowa',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kajola',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Lagelu',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ogbomosho North',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ogbomosho South',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ogo Oluwa',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Olorunsogo',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Oluyole',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ona Ara',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Orelope',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ori Ire',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Oyo East',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Oyo West',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Saki East',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Saki West',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Surulere',       'state_id' => 31, 'created_at' => now(), 'updated_at' => now()],



//Plateau State


['name' => 'Bokkos',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Barkin Ladi',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bassa',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Jos East',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Jos North',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Jos South',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kanam',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kanke',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Langtang North',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Langtang South',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Mangu',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Mikang',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Pankshin',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Quaan Pan',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Riyom',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Shendam',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Wase',       'state_id' => 32, 'created_at' => now(), 'updated_at' => now()],


          ////Rivers State

['name' => 'Abua/Odual',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ahoada East',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ahoada West',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Akuku-Toru',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Andoni',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Asari-Toru',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bonny',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Degema',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Eleme',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Emuoha',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Etche',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gokana',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ikwerre',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Khana',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Obio/Akpor',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ogba/Egbema/Ndoni',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ogu/Bolo',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Okrika',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Omuma',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Opobo/Nkoro',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Oyigbo',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Port Harcourt',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Tai',       'state_id' => 33, 'created_at' => now(), 'updated_at' => now()],




/////Sokoto State
['name' => 'Binji',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bodinga',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Dange Shuni',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gada',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Goronyo',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gudu',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gwadabawa',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Illela',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Isa',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kebbe',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kware',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Rabah',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Sabon Birni',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Shagari',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Silame',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Sokoto North',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Sokoto South',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Tambuwal',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Tangaza',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Tureta',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Wamako',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Wurno',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Yabo',       'state_id' => 34, 'created_at' => now(), 'updated_at' => now()],



////Taraba State
['name' => 'Ardo Kola',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bali',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Donga',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gashaka',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gassol',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ibi',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Jalingo',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Karim Lamido',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kumi',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Sardauna',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Takum',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Ussa',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Wukari',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Yorro',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Zing',       'state_id' => 35, 'created_at' => now(), 'updated_at' => now()],




////Yobe State
['name' => 'Bade',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bursari',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Damaturu',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Fika',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Fune',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Geidam',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gujba',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gulani',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Jakusko',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Karasuwa',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Machina',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Nangere',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Nguru',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Potiskum',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Tarmuwa',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Yunusari',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Yusufari',       'state_id' => 36, 'created_at' => now(), 'updated_at' => now()],

['name' => 'Anka',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bakura',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Birnin Magaji/Kiyaw', 'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bukkuyum',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Bungudu',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Chafe',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gummi',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Gusau',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Kaura Namoda',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Maradun',     'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Maru',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Shinkafi',     'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Talata Mafara','state_id' => 37, 'created_at' => now(), 'updated_at' => now()],
['name' => 'Zurmi',       'state_id' => 37, 'created_at' => now(), 'updated_at' => now()],



]);
    }
}
