name: Build and Deploy
on:
  push:
    branches:
      -   main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Repository
          uses: actions/checkout@master
          with: 
              php-version: '7.1'
      -   name: Speed up the packages installation process
          run: composer create-project laravel/laravel k9x
      -   name: Install Packages
          run: composer install --no-dev
      -   name: Deploy to Server
          uses: ngocquyhoang/deploy@laravel
          with:
            user: ${{ secrets.USER }}
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}
            path: "home/spitekte/"
          env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
