name: Build and Deploy
on:
  push:
    branches:
      -   main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Repository
          uses: actions/checkout@master
      -   name: Deploy to Server
          uses: ngocquyhoang/deploy@laravel
          with:
            user: ${{ secrets.USER }}
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}
            script: |
              cd /k9x
              git pull origin main
              composer install
              php artisan config:cache
              php artisan migrate --force
          env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
