name: Build and Deploy
on:
  push:
    branches:
      -   main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Repository
          uses: actions/checkout@master
      -   name: Checkout Repositorys
          run:  git pull origin main
      -   name: Checkout Repositoryss
          run:  composer install
      -   name: Checkout Repositorysss
          run:  php artisan config:cache
      -   name: Checkout Repositorysss             
          run:  php artisan migrate --force    
      -   name: Checkout Repositoryssssss   
          uses: ngocquyhoang/deploy@laravel
          with:
            user: ${{ secrets.USER }}
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}
          env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
